- name: Perform operation on databases 
  vars_files:
    - ./variables.yml
  become: yes
  hosts: stroom_dbs
  vars:
    op: 'start.sh -q'
  roles:
    - roles/stack/op

- name: Perform operation on services 
  vars_files:
    - ./variables.yml
  become: yes
  hosts: stroom_services
  vars:
    op: 'start.sh -q'
  roles:
    - roles/stack/op

- name: Perform operation on strooms 
  vars_files:
    - ./variables.yml
  become: yes
  hosts: stroom_and_proxy
  vars:
    op: 'start.sh -q'
  roles:
    - roles/stack/op
