apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: stroom-proxy-local-repo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
