version: '2.4'

services:
    
  stroom-log-sender:
    container_name: stroom-log-sender
    image: "${STROOM_LOG_SENDER_DOCKER_REPO:-gchq/stroom-log-sender}:${STROOM_LOG_SENDER_TAG:-local-SNAPSHOT}"
    volumes:
      # Volume for the crontab configuration
      - ${STROOM_LOG_SENDER_VOLUME_CONF:-../../volumes/stroom-log-sender/conf}:/stroom-log-sender/config/:ro
      # Volume for the certs/keys
      - ${STROOM_LOG_SENDER_VOLUME_CERTS:-../../volumes/stroom-log-sender/certs}:/stroom-log-sender/certs/:ro
      # A volume for each of the services that this container will ship logs for
      # Stroom
      - type: volume
        source: stroom_logs
        target: /stroom-log-sender/log-volumes/stroom
      # Stroom Auth
      - type: volume
        source: stroom-auth-service_logs
        target: /stroom-log-sender/log-volumes/stroom-auth-service
      # Stroom Proxy (local)
      - type: volume
        source: stroom-proxy-local_logs
        target: /stroom-log-sender/log-volumes/stroom-proxy
      # Stroom Nginx
      - type: volume
        source: nginx_logs
        target: /stroom-log-sender/log-volumes/stroom-nginx
    logging:
      options:
        max-size: "${STROOM_LOG_SENDER_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_LOG_SENDER_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"

