version: '2.4'

services:

  stroom:
    container_name: stroom
    image: "${STROOM_DOCKER_REPO:-gchq/stroom}:${STROOM_TAG:-v6.0-LATEST}"
    environment:
      - DOCKER_HOST_HOSTNAME=${DOCKER_HOST_HOSTNAME:-UNKNOWN}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-UNKNOWN}
      - JAVA_OPTS=${STROOM_JAVA_OPTS:- -Xms50m -Xmx1024m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=10765,suspend=n }
      - STROOM_APP_PORT=8080
      - STROOM_ADMIN_PORT=8081
      - STROOM_DEBUG_PORT=10765
      - STROOM_NODE=${STROOM_NODE:-node1a}
      - STROOM_RACK=${STROOM_RACK:-rack}
      - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
      - STROOM_JDBC_DRIVER_URL=jdbc:mysql://${STROOM_DB_HOST:-$DB_HOST_IP}:${STROOM_DB_PORT:-3307}/${STROOM_DB_NAME:-stroom}?useUnicode=yes&characterEncoding=UTF-8
      - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - STROOM_JDBC_DRIVER_USERNAME=${STROOM_DB_USERNAME:-stroomuser}
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - STROOM_JDBC_DRIVER_PASSWORD=${STROOM_DB_PASSWORD:-stroompassword1}
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://${STROOM_STATS_DB_HOST:-$DB_HOST_IP}:${STROOM_STATS_DB_PORT:-3307}/${STROOM_STATS_DB_NAME:-stats}?useUnicode=yes&characterEncoding=UTF-8
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=${STROOM_STATS_DB_USERNAME:-statsuser}
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=${STROOM_STATS_DB_PASSWORD:-stroompassword1}
      # The browser is redirected to this URL so, like the AUTH UI URL, it needs to be the advertised host.
      # Though these look similar they are both needed, one is a base path for swagger and the other is the service
      - STROOM_AUTH_SERVICES_URL=http://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/auth
      - STROOM_AUTHENTICATION_SERVICE_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/auth/authentication/v1
      - STROOM_AUTH_AUTHENTICATION_SERVICE_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}/api/auth/authentication/v1
      - STROOM_AUTH_JWT_ISSUER=${STROOM_AUTH_JWT_ISSUER:-stroom}
      - STROOM_AUTH_JWT_ENABLETOKENREVOCATIONCHECK=${ENABLE_TOKEN_REVOCATION_CHECK:-false}
      - STROOM_AUTH_CLIENT_ID=${STROOM_AUTH_CLIENT_ID:-PZnJr8kHRKqnlJRQThSI}
      - STROOM_AUTH_CLIENT_SECRET=${STROOM_AUTH_CLIENT_SECRET:-OtzHiAWLj8QWcwO2IxXmqxpzE2pyg0pMKCghR2aU}
      - STROOM_UI_URL=${STROOM_UI_ACTIVE_SCHEME:-https}://${STROOM_UI_HOST:-$HOST_IP}
      - STROOM_UI_PATH=${STROOM_UI_PATH:-/stroom/ui?prompt=login}
      - STROOM_USERS_UI_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}/s/users
      - STROOM_APIKEYS_UI_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}/s/tokens
      - STROOM_CHANGEPASSWORD_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}/s/changepassword
      - STROOM_ADVERTISED_URL=https://${NGINX_ADVERTISED_HOST:-$HOST_IP}
      # This needs to be an API token issued for a user, i.e. for the admin user.
      # Without this Stroom won't be able to make calls to it's RemoteDataSources.
      - STROOM_SECURITY_API_TOKEN=${STROOM_SECURITY_API_TOKEN:-eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6InN0cm9vbSIsImF1ZCI6IlBabkpyOGtIUktxbmxKUlFUaFNJIn0.qT5jdPWBpN9me0L3OqUT0VFT2mvVX9mCp0gPFyTVg8DkFTPLLYIuXjOslvrllJDBbqefEtqS9OwQs3RmRnZxror676stTP6JHN76YqJWj2yJYyJGuggbXjZnfTiZGO3SOxl5FP4nmRRvPxA3XqV9kippKBpHfqm5RuTpFTU8uses2iaHFm7lY4zXmKDmwVizXybBQBtpxrBNQkeQjQyg7UFkpsRO8-PmIdbTldRhGlud5VpntwI1_ahwOzK-einUJQOWrcOBmXAMPRYBI6tSLT1xS_c5XpFX1Rxoj3FGjI-Myqp_2Nt_lZuQ3h-0Qh8WkZMnWQ76G7CKawXzRAwd7Q}
      # Default the API key advance warning to 2 weeks/20160 minutes
      - STROOM_SECURITY_API_TOKEN_DURATION_TO_WARN_BEFORE_EXPIRY=${STROOM_SECURITY_API_TOKEN_DURATION_TO_WARN_BEFORE_EXPIRY:-30d}
      - ADMIN_CONTEXT_PATH=${ADMIN_CONTEXT_PATH:-/stroomAdmin}
      - STROOM_LOGGING_LEVEL=${STROOM_LOGGING_LEVEL:-INFO}
      - STROOM_PLUGINS_LIB_DIR=${STROOM_PLUGINS_LIB_DIR:-/stroom/plugins}
      - STROOM_CONNECTORS_KAFKA_DEFAULT_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - STROOM_CONNECTORS_KAFKA_DEFAULT_CONNECTOR_VERSION=2.1.1
      #- STROOM_CONNECTORS_ELASTIC_DEFAULT_TRANSPORT_HOSTS=${ELASTIC_HOST:-elastic}:${ELASTIC_BINARY_PORT:-9300}
      #- STROOM_CONNECTORS_ELASTIC_DEFAULT_ELASTIC_HTTP_URL=http://${ELASTIC_HOST:-elastic}:${ELASTIC_HTTP_PORT:-9200}
      #- STROOM_CONNECTORS_ELASTIC_DEFAULT_CLUSTER_NAME=${STROOM_CONNECTORS_ELASTIC_DEFAULT_CLUSTER_NAME:-docker-cluster}
      #- STROOM_CONNECTORS_ELASTIC_DEFAULT_CONNECTOR_VERSION=${STROOM_CONNECTORS_ELASTIC_DEFAULT_CONNECTOR_VERSION:-5.6.4}
      - STROOM_CONTENT_PACK_IMPORT_ENABLED=${STROOM_CONTENT_PACK_IMPORT_ENABLED:-false}
      - STROOM_SERVICE_DISCOVERY_ENABLED=${STROOM_SERVICE_DISCOVERY_ENABLED:-true}
      - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=${ZOOKEEPER_QUORUM:-zookeeper:2181}
      # expose this so we can set it from the shell's env vars
      - STROOM_DEVELOPMENT_MODE=${STROOM_DEVELOPMENT_MODE:-true}
      - STROOM_INTERNALSTATISTICS_BENCHMARK_CLUSTER_DOC_REFS=${STROOM_INTERNALSTATISTICS_BENCHMARK_CLUSTER_DOC_REFS:-docRef(StatisticStore,946a88c6-a59a-11e6-bdc4-0242ac110002,Benchmark-Cluster Test),docRef(StroomStatsStore,2503f703-5ce0-4432-b9d4-e3272178f47e,Benchmark-Cluster Test)}
      - STROOM_INTERNALSTATISTICS_CPU_DOC_REFS=${STROOM_INTERNALSTATISTICS_CPU_DOC_REFS:-docRef(StatisticStore,af08c4a7-ee7c-44e4-8f5e-e9c6be280434,CPU),docRef(StroomStatsStore,1edfd582-5e60-413a-b91c-151bd544da47,CPU)}
      - STROOM_INTERNALSTATISTICS_EVENTS_PER_SECOND_DOC_REFS=${STROOM_INTERNALSTATISTICS_EVENTS_PER_SECOND_DOC_REFS:-docRef(StatisticStore,a9936548-2572-448b-9d5b-8543052c4d92,EPS),docRef(StroomStatsStore,cde67df0-0f77-45d3-b2c0-ee8bb7b3c9c6,EPS)}
      - STROOM_INTERNALSTATISTICS_HEAP_HISTOGRAM_BYTES_DOC_REFS=${STROOM_INTERNALSTATISTICS_HEAP_HISTOGRAM_BYTES_DOC_REFS:-docRef(StatisticStore,934a1600-b456-49bf-9aea-f1e84025febd,Heap Histogram Bytes),docRef(StroomStatsStore,b0110ab4-ac25-4b73-b4f6-96f2b50b456a,Heap Histogram Bytes)}
      - STROOM_INTERNALSTATISTICS_HEAP_HISTOGRAM_INSTANCES_DOC_REFS=${STROOM_INTERNALSTATISTICS_HEAP_HISTOGRAM_INSTANCES_DOC_REFS:-docRef(StatisticStore,e4f243b8-2c70-4d6e-9d5a-16466bf8764f,Heap Histogram Instances),docRef(StroomStatsStore,bdd933a4-4309-47fd-98f6-1bc2eb555f20,Heap Histogram Instances)}
      - STROOM_INTERNALSTATISTICS_MEMORY_DOC_REFS=${STROOM_INTERNALSTATISTICS_MEMORY_DOC_REFS:-docRef(StatisticStore,77c09ccb-e251-4ca5-bca0-56a842654397,Memory),docRef(StroomStatsStore,d8a7da4f-ef6d-47e0-b16a-af26367a2798,Memory)}
      - STROOM_INTERNALSTATISTICS_META_DATA_STREAM_SIZE_DOC_REFS=${STROOM_INTERNALSTATISTICS_META_DATA_STREAM_SIZE_DOC_REFS:-docRef(StatisticStore,946a8814-a59a-11e6-bdc4-0242ac110002,Meta Data-Stream Size),docRef(StroomStatsStore,3b25d63b-5472-44d0-80e8-8eea94f40f14,Meta Data-Stream Size)}
      - STROOM_INTERNALSTATISTICS_META_DATA_STREAMS_RECEIVED_DOC_REFS=${STROOM_INTERNALSTATISTICS_META_DATA_STREAMS_RECEIVED_DOC_REFS:-docRef(StatisticStore,946a87bc-a59a-11e6-bdc4-0242ac110002,Meta Data-Streams Received),docRef(StroomStatsStore,5535f493-29ae-4ee6-bba6-735aa3104136,Meta Data-Streams Received)}
      - STROOM_INTERNALSTATISTICS_PIPELINE_STREAM_PROCESSOR_DOC_REFS=${STROOM_INTERNALSTATISTICS_PIPELINE_STREAM_PROCESSOR_DOC_REFS:-docRef(StatisticStore,946a80fc-a59a-11e6-bdc4-0242ac110002,PipelineStreamProcessor),docRef(StroomStatsStore,efd9bad4-0bab-460f-ae98-79e9717deeaf,PipelineStreamProcessor)}
      - STROOM_INTERNALSTATISTICS_STREAM_TASK_QUEUE_SIZE_DOC_REFS=${STROOM_INTERNALSTATISTICS_STREAM_TASK_QUEUE_SIZE_DOC_REFS:-docRef(StatisticStore,946a7f0f-a59a-11e6-bdc4-0242ac110002,Stream Task Queue Size),docRef(StroomStatsStore,4ce8d6e7-94be-40e1-8294-bf29dd089962,Stream Task Queue Size)}
      - STROOM_INTERNALSTATISTICS_VOLUMES_DOC_REFS=${STROOM_INTERNALSTATISTICS_VOLUMES_DOC_REFS:-docRef(StatisticStore,ac4d8d10-6f75-4946-9708-18b8cb42a5a3,Volumes),docRef(StroomStatsStore,60f4f5f0-4cc3-42d6-8fe7-21a7cec30f8e,Volumes)}
      # External Doc Ref Types
      #- STROOM_DOCREF_TYPES=${STROOM_DOCREF_TYPES:-AnnotationsIndex,ElasticIndex}
      #- STROOM_DOCREF_URL_SERVICE__ANNOTATIONS_INDEX=${STROOM_ANNOTATIONS_SERVICE_URL:-http://$HOST_IP/annotationsService}
      #- STROOM_DOCREF_URL_SERVICE__ELASTIC_INDEX=${STROOM_QUERY_ELASTIC_SERVICE_URL:-http://$HOST_IP/queryElasticService}
      #- STROOM_DOCREF_URL_UI__ANNOTATIONS_INDEX=${STROOM_ANNOTATIONS_UI_URL:-http://$HOST_IP/annotations}
      #- STROOM_DOCREF_URL_UI__ELASTIC_INDEX=${STROOM_QUERY_ELASTIC_UI_URL:-http://$HOST_IP/query-elastic}
      - STROOM_PROXY_DIR=${STROOM_STROOM_PROXY_DIR:-/tmp/proxy}
      - STROOM_HELP_URL=${STROOM_HELP_URL:-https://gchq.github.io/stroom-docs/}
    ports:
      - "${STROOM_APP_PORT:-8080}:8080"
      - "${STROOM_ADMIN_PORT:-8081}:8081"
      - "${STROOM_DEBUG_PORT:-10765}:10765"
    healthcheck:
      test: curl --connect-timeout 5 --max-time 10 --fail --silent --head --output /dev/null http://localhost:${STROOM_ADMIN_PORT:-8081}/stroomAdmin/healthcheck || exit 1
      start_period: 1m30s
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - ${STROOM_VOLUME_CONFIG:-../../volumes/stroom/config}:/stroom/config:ro
      - type: volume
        source: stroom_logs
        target: /stroom/logs
      - type: volume
        source: stroom_output
        target: /stroom/output
      - type: volume
        source: stroom-proxy-local_repo
        target: /stroom/proxy-repo
      - type: volume
        source: stroom_volumes
        target: /stroom/volumes
    logging:
      options:
        max-size: "${STROOM_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
