version: '2.4'

services:
    
  stroom-log-sender:
    container_name: stroom-log-sender
    image: "${STROOM_LOG_SENDER_DOCKER_REPO:-gchq/stroom-log-sender}:${STROOM_LOG_SENDER_TAG:-local-SNAPSHOT}"
    volumes:
      # Volume for the crontab configuration
      - ${STROOM_LOG_SENDER_VOLUME_CONF:-../../volumes/stroom-log-sender/conf}:/stroom-log-sender/config/:ro
      # Volume for the certs/keys
      - ${STROOM_LOG_SENDER_VOLUME_CERTS:-../../volumes/stroom-log-sender/certs}:/stroom-log-sender/certs/:ro

      # This is the base compose file for stroom-log-sender. To ship logs it needs access to shared
      # docker volumes that contain the logs to ship. To allow us to run stroom-log sender in different
      # stacks with different service to ship logs for, we use an additional override file for each
      # service that adds in the mouting of a shared named volume to a dir in /stroom-log-sender/log-volumes/.
      # These override files are defined in the named_volume_mounts dir.
    logging:
      options:
        max-size: "${STROOM_LOG_SENDER_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_LOG_SENDER_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"

